/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by build
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

const sw = self as unknown as ServiceWorkerGlobalScope & typeof globalThis;


// Handle Push Notifications
sw.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const { title, body, icon, data: payload } = data;

    const options = {
      body,
      icon: icon || '/favicon.png',
      badge: '/favicon.png',
      data: payload,
      vibrate: [100, 50, 100],
      actions: [
        { action: 'open', title: 'Abrir App' }
      ]
    };

    event.waitUntil(
      sw.registration.showNotification(title, options)
    );
  } catch (error) {
    console.error('Error handling push event:', error);
  }
});

// Handle Notification Clicks
sw.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window open
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (sw.clients.openWindow) {
        return sw.clients.openWindow(urlToOpen);
      }
    })
  );
});
